### ISSUE TITLE
Link chart finish line and y axis to race length

### ISSUE THREAD

**Issue by dariuschapman** [AcrossTheCloud/twelfth-monkey-stats#6]
currently. the finish line (ie red line on the charts) and the y-axis scale is hard-coded into the charts. need to modify this so that the finish line and the y axis max is linked to the total event length.

**Comment by matthewberryman** [comment]
fixed in https://github.com/CardiovascTech/twelfth-monkey-stats/commit/26d323161e632ccb0d7efecca1d8b071da8b83c8
